# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'com.example.crossplatform.push' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for com.example.crossplatform.push
  pod 'Firebase/Messaging'
  
  pod 'React', path: '../node_modules/react-native', subspecs: [
  'Core',
  'CxxBridge', # Include this for RN >= 0.47
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTPushNotification',
  'RCTWebSocket', # Needed for debugging
  'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  pod 'react-native-config', :path => '../node_modules/react-native-config'
  
  pod 'react-native-fcm', :path => '../node_modules/react-native-fcm'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == 'react-native-config'
              phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
              phase.shell_script = "cd ../../"\
              " && RNC_ROOT=./node_modules/react-native-config/"\
              " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
              " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
              " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
              
              target.build_phases << phase
              target.build_phases.move(phase,0)
          end
      end
  end

  target 'com.example.crossplatform.pushTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'com.example.crossplatform.push-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for com.example.crossplatform.push-tvOS

  target 'com.example.crossplatform.push-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
